[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v
markers =
    ui: UI automation tests
    api: API tests
    integration: API and UI integration tests
    mobile: Mobile/browser testing
